spring:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  datasource:
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1"
    driverClassName: "org.h2.Driver"
    username: sa
    password: password
    platform: h2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true